version: "3"
services:
  app-view:
    image: bcskda/abituz
    restart: on-failure
    networks:
      webnet:
    ports:
      - "8000:5000"
    environment:
      DATABASE_URL: mysql://abituz:<pass>@db/abituz
      APP_UPDATE_AUTO: 1
      APP_UPDATE_SECS: 1800
  db:
    image: mariadb
    restart: on-failure
    networks:
      webnet:
    volumes:
      - dbdata:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: <root pass>
      MYSQL_USER: abituz
      MYSQL_PASSWORD: <pass>
      MYSQL_DATABASE: abituz
networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
volumes:
  abituz-dbdata:
