"""add Application.score_sum

Revision ID: 691df7e8b26f
Revises: bc564f010730
Create Date: 2018-07-16 11:23:54.763236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691df7e8b26f'
down_revision = 'bc564f010730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('score_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'score_sum')
    # ### end Alembic commands ###
