"""+2 exams/scores

Revision ID: a447e499a30c
Revises: 25fcac182dba
Create Date: 2018-07-05 14:30:36.667842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a447e499a30c'
down_revision = '25fcac182dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('exam_5', sa.String(length=10), nullable=True))
    op.add_column('application', sa.Column('exam_6', sa.String(length=10), nullable=True))
    op.add_column('application', sa.Column('score_5', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('score_6', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'score_6')
    op.drop_column('application', 'score_5')
    op.drop_column('application', 'exam_6')
    op.drop_column('application', 'exam_5')
    # ### end Alembic commands ###
