"""add Application.is_budget

Revision ID: bc564f010730
Revises: 2546c46e96f4
Create Date: 2018-07-15 17:11:14.353650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc564f010730'
down_revision = '2546c46e96f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('is_budget', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'is_budget')
    # ### end Alembic commands ###
